name = "Craftaway"
author = "Schoperation"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7acc45b4cde9a6a755796e54e8404f1aee79c06c2b945b438e9304f24c0107fe"

[versions]
fabric = "0.16.3"
minecraft = "1.21"
