name = "Craftaway"
author = "Schoperation"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e96dd032bc026064b7f2a5a88783b1f0658425db950428bd4a26905b939e9b7"

[versions]
fabric = "0.16.3"
minecraft = "1.21"
