name = "Craftaway"
author = "Schoperation"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ba1aeb46cf5e5c62a13333a34bc12736aee51cec96f4f1d7b984334677707212"

[versions]
fabric = "0.16.3"
minecraft = "1.21"
