name = "Craftaway"
author = "Schoperation"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f20c9d9ef97e85b20b7d61ed6df1c6006b27e70df9eba5fd1e9bfdb66c134080"

[versions]
fabric = "0.16.3"
minecraft = "1.21"
