name = "Craftaway"
author = "Schoperation"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9eae69e9bae0e0da99175d92e678e767040ce06999e2b41d1aa4cc6203b8ba3c"

[versions]
fabric = "0.16.0"
minecraft = "1.21"
