name = "Craftaway"
author = "Schoperation"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "08bce7b4c3cee373a57648b6c870265cba2bfe0310a5e4f822e7624d0ad15cb2"

[versions]
fabric = "0.16.3"
minecraft = "1.21"
