name = "Craftaway"
author = "Schoperation"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "baf4d75167a613e8661566fb81da5538eb2b062f00fd6d95417e208ab752e17a"

[versions]
fabric = "0.16.0"
minecraft = "1.21"
