name = "Craftaway"
author = "Schoperation"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3857246ce6d0aa3749d38a9d4ac9b997bb97f17640b7e8ba61f4eff6d6727b13"

[versions]
fabric = "0.16.3"
minecraft = "1.21"
