name = "Craftaway"
author = "Schoperation"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "101c724a5e3f1727090cfac5b99f3b758d3a4a16f5f3cea2885c51ad27095dc9"

[versions]
fabric = "0.16.0"
minecraft = "1.21"
