name = "Craftaway"
author = "Schoperation"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa4442783b8bba779d289084e8439dc5c32e5ea3d0ff4f3df4e4b3b178c47c43"

[versions]
fabric = "0.16.3"
minecraft = "1.21"
