name = "Craftaway"
author = "Schoperation"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "859e43ee5a2018c291a2641ac0a412a1e9d39351e1471b03fdef0be874d4e7c9"

[versions]
fabric = "0.16.3"
minecraft = "1.21"
