name = "Craftaway"
author = "Schoperation"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "751b4fcb5e033ffe6dc71fa1538b8789ce245ed2690e9a34057e955766eb924a"

[versions]
fabric = "0.16.3"
minecraft = "1.21"
